name: frontend
description: A new Flutter project.

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.6.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true